[tools]
python = "3.14"

[tasks.pt]
description = "Render the Portuguese resume"
sources = ['Antonio Gabriel Curriculo.yaml']
run = "rendercv render 'Antonio Gabriel Curriculo.yaml'"

[tasks.en]
sources = ['Antonio Gabriel Resume.yaml']
description = "Render the English resume"
run = "rendercv render 'Antonio Gabriel Resume.yaml'"

[tasks.all]
description = "Render all resumes"
run = [{ tasks = ["pt", "en"] }]
